### PR TITLE
Implement  checkmarks

### PR DESCRIPTION
**Pull request by MasterTuto**
**Issue #34:** [link](https://github.com/AdrianSimionov/obsidian-mindmap-nextgen/issues/23)

### What has been done?

Implementation of copying to clipboard with high quality output.

### How to test it?

1. Run the plugin
2. Open obsidian or restart plugin
3. Open a markdown document
4. Type any `- [ ]` option
5. Verify the result on rendered markmap
6. If there's error or should be rendered different, ask in the comments.

### CODE REVIEW

**Comment by AdrianSimionov** [comment]
Does not seem to work, it is rendered the same, as text.

**Comment by MasterTuto** [comment]
image

is seems to work here.

Give me an markdown example that should work.

**Comment by AdrianSimionov** [comment]
From an user perspective, the unchecked character has something odd to it, but I cannot say what it is.

Can you please translate to:
**✓** bold, green, same font as the text, for checked item
and
**✗** bold, red, same font as the text, for unchecked item

I curious if it will look better.

**Comment by MasterTuto** [comment]
Fixed, it can also be the default <checkbox> html element (which can be styled to anything you want).

**Comment by AdrianSimionov** [comment]
Looks good. Please add one space after the special character.

**Comment by MasterTuto** [comment]
done

**Comment by AdrianSimionov** [comment]
@MasterTuto: Please fix the conflict and add a bit of documentation around this feature, with a screenshot.

**Pull request merged**
